
spring:
  application:
    name: user-web
  dubbo:
    application:
      name: user-web
    protocol:
      name: dubbo
      port: 20880
    registry:
      address: 127.0.0.1:2181
      protocol: zookeeper
    base-package: com.shop.user
    consumer:
      check: false
      timeout: 60000


server:
  port: 8061
logging:
  level:
    com: debug
