
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  application:
    name: cart-service
  dubbo:
    application:
      name: cart-service
    protocol:
      name: dubbo
    registry:
      address: 127.0.0.1:2181
      protocol: zookeeper
    base-package: com.shop.cart
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8131
logging:
  level:
    com: debug
