
spring:
  application:
    name: item-web
  dubbo:
    application:
      name: item-web
    protocol:
      name: dubbo
    registry:
      address: 127.0.0.1:2181
      protocol: zookeeper
    base-package: com.shop.item
    consumer:
      check: false
      timeout: 60000
  thymeleaf:
    cache: false
server:
  port: 8091
logging:
  level:
    com: debug

